In [1]:
import numpy as np

In [3]:
np.array([[1, 2, 3], [4,5,6] ], np.int32)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([1,2,3], np.float)

array([1., 2., 3.])

In [5]:
np.ones((3,2), float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
np.full((4,4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [8]:
np.ones((4,4), int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [9]:
np.empty((1,4))

array([[2.15645376e-316, 4.94065646e-324, 0.00000000e+000,
        0.00000000e+000]])

In [11]:
np.zeros((2,2), int)

array([[0, 0],
       [0, 0]])

In [15]:
x = np.arange(4)
print(x)
y = np.zeros_like(x)
print(y)

[0 1 2 3]
[0 0 0 0]


In [16]:
np.full_like(x,7)

array([7, 7, 7, 7])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [19]:
np.arange(100, 5, -2)

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6])

In [20]:
np.linspace(3,5,50)

array([3.        , 3.04081633, 3.08163265, 3.12244898, 3.16326531,
       3.20408163, 3.24489796, 3.28571429, 3.32653061, 3.36734694,
       3.40816327, 3.44897959, 3.48979592, 3.53061224, 3.57142857,
       3.6122449 , 3.65306122, 3.69387755, 3.73469388, 3.7755102 ,
       3.81632653, 3.85714286, 3.89795918, 3.93877551, 3.97959184,
       4.02040816, 4.06122449, 4.10204082, 4.14285714, 4.18367347,
       4.2244898 , 4.26530612, 4.30612245, 4.34693878, 4.3877551 ,
       4.42857143, 4.46938776, 4.51020408, 4.55102041, 4.59183673,
       4.63265306, 4.67346939, 4.71428571, 4.75510204, 4.79591837,
       4.83673469, 4.87755102, 4.91836735, 4.95918367, 5.        ])

In [25]:
x = np.ones([10,10,3])
x.reshape(1,300)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 

In [27]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.random.randint(0,10,(3,3))

array([[1, 2, 3],
       [7, 8, 4],
       [4, 0, 1]])

In [59]:
np.random.normal(0,1,(3,3))

array([[-1.27592673, -1.80203658,  0.91380518],
       [ 0.11942944, -1.11632181,  1.54281102],
       [ 0.87210663, -0.95731655, -2.50226693]])

In [54]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.sum(A), np.sum(A, axis=0), np.sum(A, axis=1)

(45, array([12, 15, 18]), array([ 6, 15, 24]))

In [60]:
np.max(A), np.average(A), np.mean(A), np.min(A), np.std(A)

(9, 5.0, 5.0, 1, 2.581988897471611)

In [62]:
np.max(A,axis=0)
np.amax(A,axis=0)

array([7, 8, 9])

In [67]:
np.min(A, axis=0)

array([1, 2, 3])

In [70]:
np.ptp(A,1)

array([2, 2, 2])

In [74]:
np.std(A), np.std(A, 0), np.std(A, 1)

(2.581988897471611,
 array([2.44948974, 2.44948974, 2.44948974]),
 array([0.81649658, 0.81649658, 0.81649658]))

In [75]:
np.mean(A), np.mean(A,0), np.mean(A,1)

(5.0, array([4., 5., 6.]), array([2., 5., 8.]))

In [81]:
A, np.median(A), np.median(A, 0), np.median(A,1)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), 5.0, array([4., 5., 6.]), array([2., 5., 8.]))

In [83]:
np.var(A), np.var(A, 0), np.var(A, 1)

(6.666666666666667,
 array([6., 6., 6.]),
 array([0.66666667, 0.66666667, 0.66666667]))

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])