In [2]:
import numpy as np

In [3]:
A = np.arange(1,13).reshape((3,4))
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
A[0][0],A[0][1]

(1, 2)

In [6]:
A[0,0], A[0,1],A[1,2]

(1, 2, 7)

In [7]:
A[2,0], A[2,1], A[2,2], A[2,3]

(9, 10, 11, 12)

In [8]:
A[:, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
A[0:2, 0:4]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
A[[0,2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [24]:
B = A[[0,2], :]
B

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [25]:
B[:, [0,3]]

array([[ 1,  4],
       [ 9, 12]])

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[4:7]

array([4, 5, 6])

In [30]:
x[0:10:2]

array([0, 2, 4, 6, 8])

In [37]:
x[:-11:-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
x[5:-2]

array([5, 6, 7])

In [39]:
x2 = np.random.randint(10, size=(3,4))

In [40]:
x2

array([[8, 3, 2, 1],
       [9, 2, 6, 2],
       [4, 2, 5, 4]])

In [43]:
x2[0,0] =100
x2

array([[100,   3,   2,   1],
       [  9,   2,   6,   2],
       [  4,   2,   5,   4]])

In [44]:
x2[0:2,0:2] = 200

In [45]:
x2

array([[200, 200,   2,   1],
       [200, 200,   6,   2],
       [  4,   2,   5,   4]])

In [5]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
x = np.array([1,2,3])
x.shape

(3,)

In [17]:
y = x.reshape((1,3))
y.shape

(1, 3)

In [20]:
x = x.reshape((1,3))

In [21]:
x.shape

(1, 3)

In [23]:
B = x[np.newaxis, :]

In [24]:
B.shape

(1, 1, 3)