In [1]:
import numpy as np

In [3]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [9]:
print("x       = x", x)
print("x  + 5  = x", x+5)
print("x  + 5  = x", x-5)
print("x  + 5  = x", x*2)
print("x  + 5  = x", x/2)
print("x  + 5  = x", x//2)

x       = x [0 1 2 3]
x  + 5  = x [5 6 7 8]
x  + 5  = x [-5 -4 -3 -2]
x  + 5  = x [0 2 4 6]
x  + 5  = x [0.  0.5 1.  1.5]
x  + 5  = x [0 0 1 1]


In [10]:
print("x  ** 2  = x", x**2)

x  ** 2  = x [0 1 4 9]


In [12]:
y =-(0.5 * x + 1)**2

In [17]:
import pandas as pd
df =pd.DataFrame(y.tolist())
df.to_csv('test.csv')

In [19]:
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [21]:
print('theta     = ', theta)
print('sin(theta)     = ', np.sin(theta))
print('cos(theta)     = ', np.cos(theta))
print('tan(theta)     = ', np.tan(theta))

theta     =  [0.         1.57079633 3.14159265]
sin(theta)     =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)     =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)     =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Aggregates

In [23]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [24]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [25]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [27]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [30]:
x = np.arange(1,6)
print(x)
x <3

[1 2 3 4 5]


array([ True,  True, False, False, False])

In [34]:
np.sum(x<3)

2

In [39]:
1 == True

True

In [40]:
x = np.random.randint(10, size=(3,4))
x

array([[9, 0, 8, 9],
       [5, 3, 7, 5],
       [1, 2, 5, 9]])

In [42]:
np.count_nonzero(x<6)

7

In [43]:
np.sum(x<6)

7