# 배열 생성 루틴

## Ones and zeros

In [5]:
import numpy as np

2*2 integers 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

In [30]:
np.array([(1,2),(3,4)], np.int64)

array([[1, 2],
       [3, 4]], dtype=int64)

X = np.array([1,2,3], [4,5,6], np.int32) 일 때,
X와 동일한 shape를 가지는 다차원 배열을 초기화 하지 않은 상태로 생성하세요.

크기가 3인 단위행렬을 생성하세요.

In [31]:
X=np.array(([1,2,3],[4,5,6]), np.int32)
np.array(X,np.int32)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
np.ones((3,2), np.float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

x = np.arange(4, dtype=np.int64) 일 때,
X와 동일한 shape를 가지고 모든 원소가 1인 다차원 배열을 생성하세요.

In [40]:
x = np.arange(4, dtype=np.int64) 
np.full_like(x,1)

array([1, 1, 1, 1], dtype=int64)

모든 원소가 0으로 채워진 3*2 실수형 다차원 배열을 생성하세요.

In [17]:
np.zeros((3,2), np.float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

x = np.arange(4, dtype=np.int64) 일 때,

x와 동일한 shape의 영행렬을 생성하세요.

In [45]:
x = np.arange(4, dtype=np.int64) 
np.full_like(x,0)

array([0, 0, 0, 0], dtype=int64)

모든 원소가 6으로 채워진 2*5 uint형(부호없는 정수) 다차원 배열을 생성하세요.

In [22]:
np.full((2,5),6, np.uint)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

x = np.arange(4, dtype=np.int64)일 때,

x와 동일한 shape이고 모든 원소가 6인 다차원 배열을 생성하세요.

In [46]:
x=np.arange(4,dtype=np.int64)
np.full_like(x,6)

array([6, 6, 6, 6], dtype=int64)

## From existing data

[1, 2, 3] 배열을 생성하세요

In [16]:
np.array([1,2,3])

array([1, 2, 3])

x = [1, 2] 일 때(python list 상태)

x를 배열로 변환하세요.

In [47]:
x = [1, 2] 
np.array(x)

array([1, 2])

x = [1, 2] 일 때(python list 상태)

x를 `float`형 배열로 변환하세요.

In [48]:
x = [1, 2] 
np.array(x, float)

array([1., 2.])

## Numerical ranges

2, 4, 6, 8, ..., 100 을 원소로 가지는 배열을 생성하세요.

In [14]:
np.arange(2,100,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

3.0 에서 10.0 까지 50개의 원소가 균일하게 분포된 1차원 배열을 생성하세요.

In [50]:
np.linspace(3,10,50)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])