In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv('data/Simple linear regression.csv')
data.head(2)

SAT   GPA
0  1714  2.40
1  1664  2.52

In [4]:
x = data.SAT
y = data.GPA
x.shape, y.shape

((84,), (84,))

In [6]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [7]:
result = LinearRegression()
result.fit(x_matrix, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [8]:
result.coef_, result.intercept_

(array([0.00165569]), 0.2750402996602803)

In [11]:
mydata = np.array(1790)
mydata = mydata.reshape(-1,1)

In [10]:
result.predict(mydata)

array([3.23872191])

In [13]:
data = pd.read_csv('data/Multiple linear regression.csv')
data.head(2)

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3

In [14]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [15]:
scaler = StandardScaler()
scaler.fit(x)

E:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
x_scaled = scaler.transform(x)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [18]:
result = LinearRegression()
result.fit(x_scaled, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [20]:
result.intercept_, result.coef_

(3.330238095238095, array([ 0.17181389, -0.00703007]))

GPA = 3.330238095238095+ 0.17181389*STA +-0.00703007* rand123

In [22]:
result_summary = pd.DataFrame([['Base'],['SAT'],['Rand 1,2,3']],
                              columns=['Featrue'])

In [24]:
result_summary['weight'] = result.intercept_, result.coef_[0], result.coef_[1]

In [25]:
result_summary

Featrue    weight
0        Base  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [26]:
new_data = pd.DataFrame(data=[[1700, 2],[1800,1]], columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1800           1

In [27]:
result.predict(new_data)

array([295.39979563, 312.58821497])

In [28]:
new_data_scaled = scaler.transform(new_data)
result.predict(new_data_scaled)

E:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


array([3.09051403, 3.26413803])

In [29]:
result.score(x_scaled,y)

0.4066811952814283